server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    path: /error
  forward-headers-strategy: framework

spring:
  application:
    name: api
    description: api-server
    is-debug: false
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:256MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:256MB}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time: iso
      date: iso
  lifecycle:
    timeout-per-shutdown-phase: 1m
  sleuth:
    sampler:
      probability: ${SPRING_SLEUTH_SAMPLER_PROBABILITY:1.0}
    async:
      enabled: true
    feign:
      enabled: true
  sql:
    init:
      mode: never
  main:
    allow-circular-references: false
    log-startup-info: false
    banner-mode: off
  devtools:
    restart:
      enabled: false

management:
  endpoint:
    health:
      enabled: true
      show-details: never
  endpoints:
    enabled-by-default: false

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    resolve-schema-properties: true
    path: /docs/openapi
  swagger-ui:
    path: /docs/swagger
    enabled: true
  packages-to-scan: com.dongeui.dongeui
  cache:
    disabled: true